// import type { Guest, GuestStatus } from './Types';

// export const GUEST_STATUSES: GuestStatus[] = ['Checked In', 'Checked Out', 'Reserved', 'VIP'];
// export const ID_TYPES = ['Passport', 'National ID', 'Driving License', 'Voter ID'];
// export const NATIONALITIES = ['Nepal', 'India', 'USA', 'UK', 'China', 'Japan', 'Australia', 'Other'];

// export const initialGuests: Guest[] = [
//     {
//         id: '1',
//         name: 'John Doe',
//         email: 'john@email.com',
//         phone: '+91 9876543210',
//         roomNumber: '201',
//         status: 'Checked In',
//         checkIn: '2026-01-18',
//         checkOut: '2026-01-22',
//         totalStays: 5,
//         totalSpent: 45000,
//         idType: 'Passport',
//         idNumber: 'AB1234567',
//         nationality: 'USA',
//     },
//     {
//         id: '2',
//         name: 'Jane Smith',
//         email: 'jane@email.com',
//         phone: '+91 9876543211',
//         roomNumber: '102',
//         status: 'VIP',
//         checkIn: '2026-01-19',
//         checkOut: '2026-01-25',
//         totalStays: 12,
//         totalSpent: 125000,
//         idType: 'Passport',
//         idNumber: 'CD7654321',
//         nationality: 'UK',
//     },
//     {
//         id: '3',
//         name: 'Mike Johnson',
//         email: 'mike@email.com',
//         phone: '+91 9876543212',
//         roomNumber: '210',
//         status: 'Reserved',
//         checkIn: '2026-01-25',
//         checkOut: '2026-01-28',
//         totalStays: 2,
//         totalSpent: 18000,
//         idType: 'National ID',
//         idNumber: 'NP123456',
//         nationality: 'Nepal',
//     },
//     {
//         id: '4',
//         name: 'Sarah Wilson',
//         email: 'sarah@email.com',
//         phone: '+91 9876543213',
//         roomNumber: '305',
//         status: 'Checked Out',
//         checkIn: '2026-01-10',
//         checkOut: '2026-01-15',
//         totalStays: 3,
//         totalSpent: 32000,
//         idType: 'Passport',
//         idNumber: 'IN9876543',
//         nationality: 'India',
//     },
//     {
//         id: '5',
//         name: 'David Brown',
//         email: 'david@email.com',
//         phone: '+91 9876543214',
//         roomNumber: '305',
//         status: 'Checked In',
//         checkIn: '2026-01-20',
//         checkOut: '2026-01-23',
//         totalStays: 1,
//         totalSpent: 9000,
//         idType: 'Driving License',
//         idNumber: 'DL789456',
//         nationality: 'Australia',
//     },
// ];
